### PR TITLE
Form data storage

### PR DESCRIPTION
**Pull request by Olamarx**
Add the local storage when the data input in the form can be saved locally.

### CODE REVIEW

**Review by ShoiraTa — APPROVED** [review]
### **STATUS: APPROVED  ✔️** 
------
Hi @Olamarx ,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

giphy

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by enniopo** [comment]
Hi @ShoiraTa - this is a pair-program activity and we should check that there are commits from both coding partners. So this PR should have been invalidated. 

Hi @Olamarx - since this is the only thing missing, can you please work with your coding partner on introducing some improvements? Please ask your partner to commit those changes. Once done, please let me know and I will manually approve the activity. 

Thanks and sorry for the inconvenience.

**Comment by andgarzonmal** [comment]
Hi @enniopo, thank you, sir. I reverted the merge action and I have made some commit as required. Please let me know if you can see my commits.

**Comment by enniopo** [comment]
hi @andgarzonmal I cannot see any commits from you.

**Comment by andgarzonmal** [comment]
Hi @enniopo, can you please explain to me how to make a commit on a pull request i made some changes to the branch so i thought those changes would be reflected on this pull request

**Pull request merged**
